### ISSUE TITLE
Apple Watch Support

### ISSUE THREAD

**Issue by xChaooticz** [twofas/2fas-ios#1]
As the title says, Apple Watch support would be amazing as sometimes i dont have the phone with me but the Watch always strapped onto my arm

**Comment by adocyn** [comment]
Hi @xChaooticz, the Apple Watch app is definitely in the plans. It's a larger functionality, so it's sandwiched between a smaller ones in product plan and as the time for development is extreeeeeemly limited we're constantly shuffling priorities trying to balance functionalities which will appease the whole community and in between, we're adding features which are requested by smaller groups.
Anyway we're close as the work on Apple Watch app was supposed to start in half of the January, but we're adding languages first. Anyway - as close as ever 😄

**Comment by bviktor** [comment]
But why are you closing the issue if it's clearly not fixed yet?
