### ISSUE TITLE
No Backup.2fas file import iPadOS

### ISSUE THREAD

**Issue by rpstbay** [twofas/2fas-ios#10]
Hello,

After installing 2FAS 4.1.1 on iPadOS 16.3.1 no Backup.2fas file import from iOS 16.3.1 is possible. Instead of the file browser the following is shown:

![image](https://user-images.githubusercontent.com/128404327/226565332-1bf61e5f-96d9-46fd-8ac0-52b01c12e791.png)

By the next attempt:

![image](https://user-images.githubusercontent.com/128404327/226565737-db746ad6-e98b-44a0-9f10-f8587b73d540.png)

After the second screen the app seems to stuck, no way out … I did several restarts, reinstalls and so on with the same results each time. To me that looks like a bug in iPadOS – in iOS the same procedure is flawless.

Many thanks for your attention and best regards

**Comment by adocyn** [comment]
@rpstbay Yes, we're opening the "file browser window" and what's inside it is out of our hands. But the 16.4 is in Release Candidate version so:
- we'll test this functionality to ensure there's nothing to fix
- it's possible it will fix this bug

If opening Backup.2fas didn't work from this location you can try to move it to "local storage" on iPad. I assume it's in the iCloud?

**Comment by rpstbay** [comment]
Hi @adocyn

Both ways I tried to import .2fas, from iCloud and local storage as well without success – so I come to the conclusion that so far there is no possibility importing a Backup.2fas file to 2FAS app on iPadOS 16.3.1. Maybe … that could change with 16.4, we will see.

However, many thanks for clarifying and keeping a eye on it!

**Comment by adocyn** [comment]
👍

**Comment by rpstbay** [comment]
👌 – very nice, thanks!RobertAm 22.03.2023 um 23:36 schrieb Zbigniew Cisiński ***@***.***>:﻿
👍
