### ISSUE TITLE
Google Authenticator import won't import account name

### ISSUE THREAD

**Issue by arigon** [twofas/2fas-ios#11]
Hello

I just moved from Google Authenticator to 2FAS with the iOS App.
It seems the import will miss the account name which is the additional info in 2FAS.

Alex

**Comment by adocyn** [comment]
Hi @arigon. Thanks, we'll check it out. Maybe something changed in the GA export format.

**Comment by adocyn** [comment]
Hi @arigon We've added some fixes with 4.2 so it should at least import this data better. But there are cases that we can't rely on GA data as they're low quality anyway so it's not perfect.
