### ISSUE TITLE
feat: Add support for group tabs

### ISSUE THREAD

**Issue by jackylamhk** [twofas/2fas-ios#119]
### Feature description

I would like the option to have groups show up in horizontal group tabs on top of the screen.

### Motivation

As the number of services grow, it becomes harder to reach to the bottom. Search helps, but tabs should get me there faster if I’m looking for a specific group.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adocyn** [comment]
Hi, we're not planning that right now. But I've added that to the backlog.
