### ISSUE TITLE
Feature request: add AppConfig for MDM

### ISSUE THREAD

**Issue by xvsun** [twofas/2fas-ios#12]
Mobile device management (MDM) are using AppConfig standard to preset and configure settings so apps can be mass deployed to devices: [https://www.appconfig.org](https://www.appconfig.org).

I think these options should be available:
- option that passcode is required
- toggle/hide Backup functionality 
- toggle/hide biometric option
- preset lockout settings
- toggle/hide browser extension

**Comment by adocyn** [comment]
Hi @xvsun,
We've added this feature to the backlog and we'll implement that in near future 👍

**Comment by 2fas-com** [comment]
We wanted to update you on the MDM feature you requested. Apologies for the delay—it took us longer than expected. We're excited to announce that it will be included in version 5.3.5 for iOS, expected in about a month. This update will incorporate essential features like disallowing iCloud backup and requiring a PIN. Thanks for your patience and your valuable input!

**Comment by adocyn** [comment]
@xvsun 5.3.5 is already in the App Store. More info: https://github.com/twofas/2fas-ios/tree/main/TwoFAS/MDM
