### ISSUE TITLE
Add a compacter "Compact" view

### ISSUE THREAD

**Issue by kaiserkiwi** [twofas/2fas-ios#134]
### Feature description

The compact view is currently saving about 10 pixel per service. The icon implies that I can get two codes per row, so maybe this is a bug report rather than a feature request.

Currently the Compact view looks like that. That looks more like it should look like that as a default.
![IMG_3539](https://github.com/user-attachments/assets/f03707c9-6365-4190-a022-fa43fef78426)

In comparison with the default view I get barely more codes visible at the same time so I'm forced to scroll or use the search. That's okay for services I use rather rarely but for the ten services I need the code regularly it's a bit cumbersome.

So my feature request would be a even compacter grid view with two services per row. As seen in the screenshot there's more that enough room without any content. If the countdown goes under the logo it saves even more space. So there's a lot of potential here.

### Motivation

This would make the app even easier to use for power users with many services.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adocyn** [comment]
Hi, we're not planning that anytime soon but I've added that to the backlog anyway.
