### ISSUE TITLE
Feature Request: Install on mac

### ISSUE THREAD

**Issue by r-hou** [twofas/2fas-ios#18]
First I would like to express my genuine admiration and appreciation for the 2FAS Auth app that you have developed. This application provides me with an outstanding two-factor authentication experience, making security easily accessible. Its clean design, ease of use, and reassuring encryption features allow users to effortlessly protect their data and privacy in my daily lives.

However, I have noticed that 2FAS Auth is currently available only for mobile devices. While this has already proven to be extremely convenient for many users, there may still be some inconvenience for those who frequently use Mac computers. Therefore, I kindly request that you consider developing a version of 2FAS Auth for Mac(not browser extention), allowing even more users to enjoy the security and convenience offered by 2FAS Auth on various devices. Thanks!

**Comment by adocyn** [comment]
Hi @r-hou, it's on the development list. I can't commit to the release date, but it will be somewhere in Q3/Q4. It will be based on current iPad app with is being improved feature by feature with every release, as some of the features are shared between iPadOS and macOS.

**Comment by r-hou** [comment]
> 

It's great to hear that this feature is on the development list. I am looking forward to it, many thanks!!!

**Comment by ChrisBegley** [comment]
Hi @adocyn , is the macOS app still on track for 2023? If not, can you enable the ability for us to install the iPad app from the Mac App Store on our Apple silicon Macs?

**Comment by dawidry** [comment]
+1 for dedicated macOS app or at least ability to install iPad version on Apple Silicon Macs.

**Comment by dagdrommer** [comment]
Is there any update? I'd love to see the app on my Mac.

**Comment by calebcbaker** [comment]
+1 for making the iPad version installable on apple silicon macs, that's super easy to do.

**Comment by timkgh** [comment]
> adocyn closed this as completed on Apr 27, 2023

But is it really "completed"?

**Comment by brandon-fryslie** [comment]
Everyone says "2fas" is great, but lack of a desktop app is a complete non-starter...would anyone care if we forked the code and release it for MacOS?  Seems pretty reasonable since for whatever reason the iPad version has been removed from the App Store.
