### ISSUE TITLE
Allow users to customize icons for services

### ISSUE THREAD

**Issue by foru17** [twofas/2fas-ios#19]
As a user of 2fas, I have noticed that many of the services I have added do not have icons available. Unfortunately, the current app only allows the addition of brand icons that already exist. In order to enhance user experience and make the app more visually appealing, I suggest adding a feature that allows users to customize and choose their own icons for added services.
This feature would be especially helpful for services that do not have premade icons available, and would allow for greater personalization and organization within the app.
Thank you for your consideration!

**Comment by adocyn** [comment]
Hi @foru17, for now the 2FA app has the "Label" functionality, which will be overhauled in upcoming releases. We don't have plans for adding own graphics but there is a plan for some batch of generic icons which can in case of missing service icon. Also if you're missing service icon you can let us know on our Discord.

**Comment by LawnSounds** [comment]
I don't think this issue should be closed as it's still open in the Android repo (and would be a great addition): https://github.com/twofas/2fas-android/issues/6

Regarding image sizes, a solution could be only allowing SVGs - which would also limit files sizes (and maybe allow them to be iCloud synced?)
