### ISSUE TITLE
Load Yubikey with TOTP from unencrypted Backup.2fas. 

### ISSUE THREAD

**Issue by BobDenny** [twofas/2fas-ios#2]
I just wrote a stupid simple Python app that reads an unencrypted Backup.2fas and uses the Yubikey ‘ykman’ command line app to load up a Yubikey with TOTP tokens. Install free Youbico Authenticator app and you can use the key to get your 6 digit OTPs. I know that’s what 2FAS does, and I know that putting an unencrypted Backup.2fas anywhere is seriously stupid, but it’s really cool that you allow exporting unencrypted so we can do stuff like this. I erased it.

**Comment by adocyn** [comment]
Yeah, not secure at all, but sometimes you just want to move on to another app or like have a secure storage somewhere. Or just experiment. And it's your data 👍
