### ISSUE TITLE
Pairing Failed!

### ISSUE THREAD

**Issue by zhuxiucai** [twofas/2fas-ios#23]
iOS
mac

the extension can't be pairing right.

i tried reinstall both extension and apps, did not fix

**Comment by adocyn** [comment]
Hi @zhuxiucai, we're seeing those problems when Firebase Messaging Server couldn't be reached e.g. from Mainland China or if someone is using a VPN which blocks those connections. So first question - where are you located and are you using VPN?

**Comment by totoCZ** [comment]
Same issue

You are visiting from [2804:14d:5c5e:5a83:493b:2927:64a6:8580](https://bgp.he.net/ip/2804:14d:5c5e:5a83:493b:2927:64a6:8580)Brazil
Announced as [2804:14d:5c5e::/48](https://bgp.he.net/net/2804:14d:5c5e::/48) (CLARO S.A.)Brazil
Announced as [2804:14d:5c00::/40](https://bgp.he.net/net/2804:14d:5c00::/40) (Claro NXT Telecomunicacoes Ltda)Brazil
Your ISP is [AS28573](https://bgp.he.net/AS28573) (Claro NXT Telecomunicacoes Ltda)
