### ISSUE TITLE
Suspicious requests

### ISSUE THREAD

**Issue by ghost** [twofas/2fas-ios#26]
Every time I open the application on NextDNS I get these requests 🤔

https://imgur.com/a/VeukfBw

**Comment by 2fas-com** [comment]
These are anonymous crashlytics that help us fix problems. If you want to disable them, you can go to the "About" section in the settings and turn them off with a toggle.

**Comment by 2fas-com** [comment]
Thank you for bringing this to our attention. The option still works, and no crashlytics are sent, but we'll look into what causes these requests and whether we can block them.

**Comment by valynor** [comment]
Related question, what are the connections to api2.2fas.com for?

**Comment by enzor00** [comment]
> Thank you for bringing this to our attention. The option still works, and no crashlytics are sent, but we'll look into what causes these requests and whether we can block them.

I look forward to a resolution of the problem

**Comment by enzor00** [comment]
> Thank you for bringing this to our attention. The option still works, and no crashlytics are sent, but we'll look into what causes these requests and whether we can block them.

Thank you, I look forward to a resolution

**Comment by 2fas-com** [comment]
The api2.2fas is used for our Browser Extension and notifications.

**Comment by drlaserdev** [comment]
I have the same issue, even though the option is disabled, the app still communicates with firebaselogging-pa.googleapis.com.

**Comment by 2fas-com** [comment]
@ghost Could you confirm if the problem still persists? We cannot find any Firebase records. We also checked using NextDNS, as you did. I have attached two screenshots for your reference: one with 'Send anonymous crash reports' enabled and the other with it turned off. 

Turned Off:
<img width="554" alt="turned_off" src="https://github.com/twofas/2fas-ios/assets/78911177/9fdc4b7b-2a5c-45f3-adf8-e964a31d05cb">

Turned On:
<img width="580" alt="turned_on" src="https://github.com/twofas/2fas-ios/assets/78911177/64f7efa5-71ba-467f-a511-37126749ebd7">
