### ISSUE TITLE
Feature Request: Display Key as QR Code

### ISSUE THREAD

**Issue by MajorTomDE** [twofas/2fas-ios#3]
Hey,

it would be great to have an option to display a QR Code (Key + Name + Additional Info)

This helps to share the item with others or with other apps (show on iPad / scan on iPhone)

My old OTP app has this feature and with this it was so easy to move to 2fas :-) 

Thank you
Tom

**Comment by 2fas-com** [comment]
You can see all of it while editing a token! Additionally we're working on some safe and easy way to share individual tokens ✌️
