### ISSUE TITLE
Feature request: add settings toggle to remove "Notifications" tab

### ISSUE THREAD

**Issue by dmcg10** [twofas/2fas-ios#30]
I'm sure I'm not the only one that feels this tab is useless and only serves to clutter the UI.

Please give users the ability to remove it.

**Comment by 2fas-com** [comment]
Hi, thanks for the request. Yes, you're right, and we're already planning to remove it in the near future.

**Comment by FrankyFFV** [comment]
As soon as I opened the application, it was the first thing I thought of. This tab is superfluous. Waiting for the possibility to remove it.

**Comment by FrankyFFV** [comment]
> Hi, thanks for the request. Yes, you're right, even though it's the first request about it, we're already planning to remove it from the bottom bar in the near future.

As soon as I opened the application, it was the first thing I thought of. This tab is superfluous. Waiting for the possibility to remove it.

**Comment by adocyn** [comment]
The notification tab was moved to an icon on main screen in 5.0.
