### ISSUE TITLE
Feature Request: Replace option to view next token with the option to view the prior token.

### ISSUE THREAD

**Issue by mketab** [twofas/2fas-ios#31]
This functionality is much more useful as it allows you to continue typing the OTP you initially saw while it's still valid, rather than having a 5 second timeframe to start typing a new OTP. This is a default option in RaivoOTP and significantly improves usability.

![image](https://github.com/twofas/2fas-ios/assets/96551349/af6402f9-36aa-4754-bcf5-4171d3547074)

**Comment by adocyn** [comment]
@mketab Hi, it makes sense. We'll consider it, thanks.

**Comment by 2fas-com** [comment]
After our brainstorming session, we decided that we will not introduce this feature currently for two main reasons. Firstly, we do not have a lot of requests for it. Secondly, introducing outdated code, as you are likely aware, is not an elegant solution. While we recognize that many websites accept this, we believe it is not best practice.
