### ISSUE TITLE
Feature Request: multiple oauth2 tokens for one domain

### ISSUE THREAD

**Issue by qeWait** [twofas/2fas-ios#32]
I have several Google accounts, each of them has an authenticator, but after I remember the choice for the **google.com** domain, I am offered only to send or refuse, there is no "Choose another" option. So I suggest adding the option of multi-tokens for one domain

**Comment by adocyn** [comment]
@qeWait Hi, yes, we're aware of that issue and will implement a solution for that 👍

**Comment by adocyn** [comment]
@qeWait  This should be available in 5.1. You'll probably need to unpair existing pairings (Edit Service -> Browser Extension -> remove the pairing there).
