### ISSUE TITLE
Feature Request: service ordering

### ISSUE THREAD

**Issue by pzbitskiy** [twofas/2fas-ios#34]
I noticed backup file has `order` property, but no such option in the app.
Please consider adding the ordering feature to allow most used token to be at the top of the screen.

I'm not really familiar with iOS development or Swift but looks it relatively easy to implement with `tableView` as seen in [this SO answer](https://stackoverflow.com/questions/68148032/manually-set-list-order-in-swift-ios).

**Comment by acrostich** [comment]
If you go to the Edit screen for the tokens then there’s a sorting option to right of the screen.
