### ISSUE TITLE
Next release targeting 16.4?

### ISSUE THREAD

**Issue by Felting** [twofas/2fas-ios#37]
Does this mean that it will only run on 16.4 and above or it will be built on 16.4?

**Comment by adocyn** [comment]
Hi @Felting , it will only run on iOS 16.4 and up.

**Comment by Felting** [comment]
> Hi @Felting , it will only run on iOS 16.4 and up.

Oh ok, hopefully a solution will be found for older iphones and software versions.

**Comment by adocyn** [comment]
@Felting Version 4.5 will continue to work for older devices just fine. There just a handful of very old devices which do not support iOS 16 and it's a real effort to keep supporting iOS 15.4 and refrain from using the new APIs. Especially that iOS 17 will be live in upcoming weeks and we'll have to still support two versions of iOS at once.
