### ISSUE TITLE
Excessive amounts of logging

### ISSUE THREAD

**Issue by drlaserdev** [twofas/2fas-ios#38]
Recently I migrated from Raivo OTP to 2FAS because the original developer of that app sold it to some shady no-name company. What bothers me is that there are an excessive amounts of logging, even when the anonymous crash reports setting is disabled. ![image](https://github.com/twofas/2fas-ios/assets/68287010/b6be40fc-c441-4639-bf87-3b278203ddcf) Why? If you claim to respect users privacy and anonymity, why isn't there a setting to disable this?

**Comment by drlaserdev** [comment]
Oh okay, thank you for the explanation. Perhaps you should consider something more private or even self host-able like SupaBase or PocketBase as an alternative to Google Firebase, though I'm not sure they provide a crashlytics alternative. Sentry.io might be great too.

**Comment by adocyn** [comment]
@drlaserdev yeah, we had Sentry connected, but then people complained about it 🙂

**Comment by 2fas-com** [comment]
You can disable Firebase crash reports by going to Settings -> About -> Send anonymous crash reports.
![crash](https://github.com/twofas/2fas-ios/assets/78911177/2ebbc10a-69c2-452f-82a8-e9c198df28a9)
