### ISSUE TITLE
Twitch totp doesnt work because 2FAS doesnt support 10 second refresh time

### ISSUE THREAD

**Issue by slrgt** [twofas/2fas-ios#40]
Twitch uses a 7 digit code and 10 second refresh time so it doesn't work with 2FAS. I'm coming from raivo and it didnt detect it from the json (it said imported 45 of 45 tokens even though there was 46 tokens) and it's impossible to manually add it because there's no option for 10 second refresh times

**Comment by adocyn** [comment]
Hi, @slrgt, I've checked it and it's actually 20 seconds and yes, 7 digits. But we have to check if it's even a standard TOTP algorithm. E.g. Steam has it's own, totally non-standard algorithm. It seems that it's a great way to lock users only to their own or associated 2FA app.

**Comment by slrgt** [comment]
oh I think it's not non-standard since it works on other 2FA apps like Raivo but I'm not positive. Anyways thanks for the reply and the project!

**Comment by 2fas-com** [comment]
We checked, and Twitch is functioning properly. The 7-character code is used for SMS messages. However, if you wish to use the 2FAS Auth, you need to activate it as shown in the pictures below.

<img width="589" alt="step1" src="https://github.com/twofas/2fas-ios/assets/78911177/8d3125da-255d-4d22-b330-71a71c0563c8">

<img width="579" alt="step2" src="https://github.com/twofas/2fas-ios/assets/78911177/68d15ff9-01b2-4453-a2cc-a7c098d7792e">

<img width="586" alt="step3" src="https://github.com/twofas/2fas-ios/assets/78911177/b57e5d8a-b9af-4ee8-9cee-8f04c9390e72">
