### ISSUE TITLE
Raivo OTP import silently skips entries having secret seeds with spaces

### ISSUE THREAD

**Issue by foobar-1676** [twofas/2fas-ios#42]
Steps to reproduce:

1. Create a token in Raivo OTP making sure to add spaces in the secret seed
2. Export to ZIP, then unzip it
3. Import the .json into 2FAS
4. The token in question is silently skipped

This is made particularly serious by the present context: Raivo's main dev quietly sold out the whole community who gathered around his app to some dubious company with unclear privacy practices and then walked away whistling, so we can expect a lot of Raivo OTP users coming over to 2FAS, and they'll lose some of their tokens because of this bug.

**Comment by adocyn** [comment]
@foobar-1676 Hi, upcoming 5.0 should handle that scenario better 👍

**Comment by adocyn** [comment]
@foobar-1676 Please check if 5.0 did fix this issue for you.
