### ISSUE TITLE
fix/UI resets to top after revisiting

### ISSUE THREAD

**Issue by JULl4N** [twofas/2fas-ios#44]
1. Scroll a bit lower to your codes
2. Exit the app or switch to another app
3. Revisit the app -> the UI now loads with the top code

This is quite annoying if you're moving in/out of the app.

**Comment by JULl4N** [comment]
> @JULl4N Hi, do you have a PIN/biometry login enabled?

I'd swear it was happening without PIN/biometry when I was setting up 2FAS and switching between 2FAS and Google Auth.

Now I'm trying to reproduce. But indeed you're right it only happens with PIN/biometry login enabled. Maybe because Face ID is so quick I didn't notice it before and forgot I had it enabled already.

**Comment by adocyn** [comment]
That issue is fixed in upcoming 5.2.0.
