### ISSUE TITLE
fix/User does not get informed when codes are imported

### ISSUE THREAD

**Issue by JULl4N** [twofas/2fas-ios#45]
1. Import Google Auth tokens 'Choose QR code'
2. User chooses QR and clicks Continue
3. The 'Import tokens' modal shows up again with options to Scan/Choose -> however, the codes from step 2 have been imported, but user does not get informed of this

User now has to click cancel, and then switch from Settings to Tokens to see they have been imported.

Solution: after step 2, move the user to the Tokens UI, or first give options 'import more' 'done' and import more -> step 3, done -> Tokens UI

**Comment by adocyn** [comment]
@JULl4N For most imports there's a summary window with imported/total codes information. We'll check it out and add such summary if it's missing

**Comment by adocyn** [comment]
This issue should be fixed in newest version.
