### ISSUE TITLE
Strip whitespace from service pairing verification token

### ISSUE THREAD

**Issue by hehadastory** [twofas/2fas-ios#46]
When clicking "Copy token" in the iOS app during the initial service pairing process, the space between the first and last 3 digits remains, causing errors when pasted. This doesn't happen in normal use i.e. copying TOTPs from previously paired services.

I'm using v5.0.0

**Comment by adocyn** [comment]
@hehadastory This should be fixed in 5.1

**Comment by hehadastory** [comment]
@adocyn Amazing, thanks - working for me!
