### ISSUE TITLE
Install older versions of the app on older devices (AppStore)

### ISSUE THREAD

**Issue by kuflierl** [twofas/2fas-ios#49]
Since the last update (5.0) the minimum requirement for the app was set to iOS 16.4. People with older devices still on iOS 15 will not be able to install your app at all. An [apple community thread](https://discussions.apple.com/thread/253353033?&previousThread=252798224021) claims that the developer can enable the install of old versions of the app (4.5). Would this be possible?

**Comment by kuflierl** [comment]
This issue complements #37

**Comment by adocyn** [comment]
@kuflierl It is enabled, but it works only for users who already downloaded that version. New users will have to download the newest one.

**Comment by adocyn** [comment]
@kuflierl It is enabled, but it works only for users who already downloaded that version. New users will have to download the newest one.
