### ISSUE TITLE
2FAS extension not working on PayPal 

### ISSUE THREAD

**Issue by snowbound** [twofas/2fas-ios#5]
Using 2FAS on iOS 15 and extension in Vivaldi browser on 110.0.5481.111 . Go to Paypal and request a token. A notification pops up on iPhone and approves the request. Only the first  digit followed by the last digit in the token are inputted into the squares on Paypal

**Comment by GovernorWIN** [comment]
I have the same problem for a while now. Android 13 and Chrome 110.0.5481.178 . Only the first two digits get filled. Perhaps a chromium problem.

**Comment by snowbound** [comment]
Strange that it fills in the first two positions of the 2FA boxes with the first and LAST digit of the OTP that it generates leaving the remaining position blank.

**Comment by GrzegorzZajac000** [comment]
Sorry for the late reply. It will be fixed in Browser Extension v1.4.0 which is already in testing ;)

**Comment by GrzegorzZajac000** [comment]
New version of Browser Extension is released 😃
