### ISSUE TITLE
Import file version

### ISSUE THREAD

**Issue by PatrikTrefil** [twofas/2fas-ios#50]
Situation: Export data from Laspass Authenticator app using iOS app. Import the data into 2FAS app.

Expected behavior: The data is imported.

Actual behavior: Error, this file is in a newer format version than the one the app supports.

**Comment by adocyn** [comment]
@PatrikTrefil Thanks, we'll check it out

**Comment by thatcow** [comment]
Same issue for me. JSON file and QR codes both don't work.

**Comment by adocyn** [comment]
That should be fixed in newest version
