### ISSUE TITLE
Feature Request: Support Cloud Backup between IOS and Android

### ISSUE THREAD

**Issue by dtantono** [twofas/2fas-ios#51]
Hi
Like Whatsapp, they allowed sync between iOS and Android. Personally, I use IPhone and Android and Is it possible to support cloud backup between 2 platforms?

**Comment by adocyn** [comment]
Hi @dtantono, no, with current architecture, where every platform uses it's native cloud, it's impossible. Also most of our users use only one platform, so building a separate service (with all the costs and complications associated with it) doesn't make sense for such small audience. We're continuing to support files exchange (import/export) which works on both platforms.
