### ISSUE TITLE
Enter Secret Key Manually does not save entry

### ISSUE THREAD

**Issue by justinmahendra** [twofas/2fas-ios#52]
It has seemed that keying details manually will not add the totp to the app. It ends at "Almost Done", To finish pairing the service, you need to retype this token.

Once user clicks "X" button, the entry never existed. If additional information is keyed, the entry will pop up in the list, but as "X" is clicked, the entry is gone again.

**Comment by adocyn** [comment]
@justinmahendra We can't recreate it, but it's probably something with your installation. It would help us if we can get logs from your app. We can then diagnose what's going on. To do that I have to send you an unique code. When you'll scan it (or open the link), it will send us logs from your app. But I can't leave it here, out in the open, and you don't have any contact info on your github page. You could reach me on our community Discord or my mastodon account (on my github profile page).
