### ISSUE TITLE
iOS widget - Font size too small for PIN code. 

### ISSUE THREAD

**Issue by subeeshan** [twofas/2fas-ios#53]
Starting version 5.1, the font is too small for the iOS widget (PIN code), it was fine till version 5.0. Screenshot below. 
<img width="176" alt="Untitled" src="https://github.com/twofas/2fas-ios/assets/90148731/071c7774-6adb-4f64-a0a8-ed57d1622943">

**Comment by adocyn** [comment]
@subeeshan Hi, yes, we're aware that new SDK + new iOS 17 is a disastrous combination for the widgets. Fixes are coming in 5.3.

**Comment by adocyn** [comment]
Released.
