### ISSUE TITLE
Recovery method if iOS app were to disappear

### ISSUE THREAD

**Issue by aChrisYouKnow** [twofas/2fas-ios#54]
If 2FAS were to disappear from the iOS App Store, is there a documented way to decrypt the encrypted .2fas backup files? I'm aware the project is open source, but, if I didn't want to wait, or trust someone else to create a new app from the source code, it would be nice to have an option available. Creating a test encrypted .2fas file and extracting the contents to know it can be done would be nice. Thanks!

**Comment by adocyn** [comment]
@aChrisYouKnow Hi, that's why this project is open-source. We're not planning a separate tool for that right now, but as this is industry standard AES-GCM encryption and code is available, then the community should have no problem in creating such a tool.

**Comment by hwmaier** [comment]
FYI, such a community based tool already exists: https://github.com/wodny/decrypt-2fas-backup
