### ISSUE TITLE
Request for a build guide for the app

### ISSUE THREAD

**Issue by dragonandy** [twofas/2fas-ios#55]
I am interested in using 2fas and build it myself to sideload to my old iphone(ios below the requirement), but I could not find any instructions on how to build it from source.Dose the project provide the build guide for 2fas? I find it's difficult to figure out by myself.

**Comment by adocyn** [comment]
Hi @dragonandy. Take some older release from `main` branch and use this instructions https://github.com/twofas/2fas-ios/blob/main/CONTRIBUTING.md (it's a link to the current version). There's just a few files to be replaced. The version you'll build will be a fully functional 2FA client, but it won't be fully compatible with 2FAS e.g. you can't open 2FAS internal database with it. But if you set it up from scratch it will work normally. You can even import non-encrypted 2FAS backup files.
