### ISSUE TITLE
Unable to import backup from Android to iOS...

### ISSUE THREAD

**Issue by TheRealMystic** [twofas/2fas-ios#58]
iOS version: 5.1.1
Android version: 5.1.0

The iOS app gives an error when trying to import backup created by the Android app. There are two different errors shown, depending on whether the backup file is encrypted or not. Please check out the errors in the attached screenshots.

Please note that this problem started only after the Android app was updated to version 5.1.0. It was fine before the update.

**ENCRYPTED BACKUP**

![Encrypted](https://github.com/twofas/2fas-ios/assets/54448474/d3eabea7-6897-47db-9298-77551a4b7abf)

**UNENCRYPTED BACKUP**

![Unencrypted](https://github.com/twofas/2fas-ios/assets/54448474/b84ffb84-dfef-4771-afd8-666fe4edc64d)

**Comment by adocyn** [comment]
Hi @TheRealMystic Fixed in 5.1.2
