### ISSUE TITLE
 Figma token not showing up in 2fas app 

### ISSUE THREAD

**Issue by tuanson84uk** [twofas/2fas-ios#59]
Hello, 

I am writing to report a problem with the 2fas app on iOS. I have successfully added a Figma token to the app, but it does not show up in the list of accounts. I have also tried to restart or even reinstall the app, but the problem persists. This is very frustrating and inconvenient, as I need the Figma token to access my Figma account and projects. 

I wonder if anyone else has faced the same issue as me, and if there is a solution or a workaround for it. Please advise me on how to fix this problem as soon as possible. 

Thank you for your help and support. 

**Updated: Actually it automatically moved to Trash for some reason...**

**Comment by adocyn** [comment]
@tuanson84uk Hi,

We're aware about that bug. It's connected with iCloud sync or, being more precise, of the device going out of sync with iCloud.
**No services are lost**, as they're moved to the trash and it's very rare, but we'll try to fix it in upcoming releases.

**Comment by adocyn** [comment]
Relese 5.3.5 contains fix.
