### ISSUE TITLE
Feature: Choose theme (settings)

### ISSUE THREAD

**Issue by worldsdream** [twofas/2fas-ios#63]
There is no option for us to choose the “Dark” or the “Light” theme.

It’s following “System default” as of now.

Can you add the option so we can choose:

System default
Dark
Light

This is how all the other apps are doing it. I uploaded a screenshot.

Thank you.
![IMG_1642](https://github.com/twofas/2fas-ios/assets/12443285/4d332afa-c4bf-4851-8a28-a8befd83b6a2)

**Comment by adocyn** [comment]
@worldsdream Hi, currently we don't have any plans for adding an override for system settings.
