### ISSUE TITLE
Feature request: Some way to export tokens to other apps

### ISSUE THREAD

**Issue by sanjeevstunner** [twofas/2fas-ios#64]
I appreciate the work you guys put in the app. I’ve been using it for years now and I really like it, but when I recommend it to a friend, the thing that comes up is, it offers importing token from the other apps, but when they want to switch again, there’s no way, and this has come up more than once, can you guys add a way to export tokens, for at least google authenticator, as thats the basic thing most other apps support, so we can use it as a bridge. It’s a must need, try considering, thanks for the time. Have a good day

**Comment by joeri-juramento** [comment]
ℹ️ #28 #35

**Comment by KobeW50** [comment]
Closing as a duplicate
