### ISSUE TITLE
OSWatch Support

### ISSUE THREAD

**Issue by AndyXheli** [twofas/2fas-ios#66]
Hello. It would be nice to have an option to have an app for Apple Watch

**Comment by Cfrolich13** [comment]
First of all, I'm not a maintainer. I completely agree that watchOS support would be great. These two issues confirm that it will be available in the future: #1 #16

**Comment by ricardopereira** [comment]
There's #33 too. I hope this gets out soon 🥰

**Comment by KobeW50** [comment]
Duplicate of https://github.com/twofas/2fas-ios/issues/33
