### ISSUE TITLE
2fas 5.2.0 bloated up heavily?

### ISSUE THREAD

**Issue by fcore117** [twofas/2fas-ios#67]
I wanted to update to 5.2.0 which is not even here Github, but i cancelled as size have bloated up massively. Keeping 5.1 currently. What is going on as i only install light software and suddenly this?

**Comment by adocyn** [comment]
@fcore117 Hi, we've identified the issue and we'll fix it in upcoming release

**Comment by adocyn** [comment]
5.2.5 should fix the issue.

**Comment by 2fas-com** [comment]
Version 5.2.5 is already in testing, and if everything goes well, we'll have it out in a week. Thanks for pointing this out, and we're sorry for any trouble it might have caused!
