### ISSUE TITLE
2FAS Incompatible with iPhone 7

### ISSUE THREAD

**Issue by SilasReinagel** [twofas/2fas-ios#68]
The App Store version of the 2FAS requires iOS 16+, which makes this app, which formerly worked on iPhone 7 now incompatible.

What solutions are there?

**Comment by 2fas-com** [comment]
We understand your concern about the iOS 16+ requirement for the latest version of the 2FAS app.
Our commitment to security leads us to support only those operating systems that Apple currently supports.

You can continue using an older version of 2FAS, but please be aware of potential security risks.
For optimal security and compatibility, we recommend upgrading your device.

**Comment by T0xIcB3ast** [comment]
@2fas-com What a bullshit reply you guys got there!

And who said Apple doesn't support iPhone 7? As far as I can see the latest update [15.8](https://support.apple.com/en-us/109032) was released on October 2023, which was very close to your [5.1.0 release](https://github.com/twofas/2fas-ios/releases/tag/vv5.1.0) 🤔
At least be honest and they you made the requirements higher than they should be.

While there could be some security concerns, we're talking about a damn MFA app, which could be used entirely offline. This means that OP could install the app, add the token and then use his iPhone 7 entirely offline.

@SilasReinagel I have a newer device, but if I were you, I would just move to [Ente Authenticator](https://github.com/ente-io/auth#readme). They support iOS 12 devices (like basic apps like this, should). Every time I look into 2FAS Github issues, I remember why this app is doomed to fail!
