### ISSUE TITLE
Import error from LastPass Authenticator on iOS

### ISSUE THREAD

**Issue by sarg3nt** [twofas/2fas-ios#69]
Just found out about 2FAS and am trying it out.  I see it can import from LastPass Authenticator but it does not work. Says import error, file is too new of a version.
Searched through previous tickets and looks like this has happened before.

2FAS iOS version is 5.2.0
Lastpass Authenticator Version: 2.15.0.1421
I took a look at the accounts.json file that the LastPass Auth app generated and some of the relevant data is
```json
{
    "deviceName": "iPhone16,2",
    "version": 1
}
```

**Comment by sarg3nt** [comment]
Tried the QR code option and that also does not work.

**Comment by StarryFire** [comment]
I would suggest screenshotting the QR code for each individual token from last pass and then porting them over to 2FAS manually.

**Comment by martinvw** [comment]
I would love to switch to 2FAS, however, I face this same issue, is this something we can assist in?
