### ISSUE TITLE
Document Storage Place

### ISSUE THREAD

**Issue by niwre2019** [twofas/2fas-ios#7]
Hello,
I am using 2FAS Auth on my iPhone and my iPad. In the system settings I can select Nextcloud and a few others as document storage besides iCloud.
What does that mean exactly, will the data then not be stored in iCloud but on my local Nextcloud instance?
Regards

**Comment by adocyn** [comment]
Hi @niwre2019,

I suspect that's for Files functionality only. 2FAS saves data using CloudKit and that's available only for iCloud.

**Comment by niwre2019** [comment]
I'd rather leave the settings on iCloud then. Would be a great feature though to be able to save the data to the local Nextcloud instance.
Thanks a lot for your help.
