### ISSUE TITLE
Push notifications on iPhone from browser extension

### ISSUE THREAD

**Issue by sarg3nt** [twofas/2fas-ios#70]
I'm getting the notifications in the app when it's open but if the app is not currently open I don't, i.e. there's no iOS banner push notification that I can click that will then open the app and allow me to hit approve.
The Microsoft Authenticator app does this for some of their accounts.
Is this a thing it's supposed to do or is this not a feature?
If it's not a feature, is it on the roadmap.  This would make approving 2FA requests vastly easier.  
Thanks!

2FAS iOS version is 5.2.0
Safari browser extension 1.5.0

**Comment by adocyn** [comment]
Hi @sarg3nt,
Please check the Push Notification settings for the 2FAS app in system settings as this is implemented and I've just checked if it works. It does 🙂
