### ISSUE TITLE
Cross-platform Android/iOS sync

### ISSUE THREAD

**Issue by timkgh** [twofas/2fas-ios#73]
Synchronize between Android and iOS.

**Comment by 2fas-com** [comment]
Currently, we will not be implementing synchronization between two different platforms. We rely on native Apple environment for iOS applications and a secure space for data storage on Google Drive for Android. It is important to note that accessing 2FAS data from other apps or the web is not possible by simply connecting to Google Drive, as it is a protected resource. This approach offers a more secure solution. At this time, we do not plan to develop our own cloud for synchronization support.

The only available option currently is to manually export data from one phone and import it onto another.

**Comment by duckworth** [comment]
I get where you're coming from with prioritizing security and sticking to native environments for iOS and Android, but not allowing cross-platform synchronization feels like a missed opportunity, especially for an open source app. Extensibility is a big part of what makes open source software so valuable; it's all about giving users the freedom to tweak and integrate their tools in ways that best suit their needs. Iin today's world, folks often use multiple devices across different platforms, so finding a secure yet user-friendly way to sync could really boost the app's usefulness and appeal.

**Comment by timkgh** [comment]
Missed opportunity indeed. This was the biggest appeal of Authy: Android, iOS, desktop. It's 2024, people use multiple platforms, these should be table stakes features.

**Comment by lovitus** [comment]
unable to let 2fas auth as my only authenticate app. because unable to sync between my ios and android , please consider about it again

**Comment by nice2cu1** [comment]
It's 2026 now, and we still don't have the ability to synchronise across platforms. Your own cloud synchronisation scheme is not the only solution. Why don't you consider other schemes, such as users deploying their own synchronisation servers?

**Comment by timkgh** [comment]
In 2026, why are you still using 2FAS? Move to [Ente Auth](https://ente.com/auth/), which you can even self host.
