### ISSUE TITLE
New user, suggestion changes (trivial tweaks and expanded passcode options)

### ISSUE THREAD

**Issue by jdknight** [twofas/2fas-ios#75]
New user to 2fas user, loving it so far. Noticed some small things and figured it may help posting it here for consideration.

- [ ] Introduction paragraph text formatting issue
- [ ] Denied camera presentation on import screen
- [ ] QR code scan page may be better with scroll hint
- [ ] Additional passcode options

----

The introduction paragraph text on the last page is cut off (using iPhone SE):

![image](https://github.com/twofas/2fas-ios/assets/1834509/b1c52557-ef2a-4899-8421-a544623e4989)

If the camera has not been permitted for the application, the QR code section shows a helpful message:

![image](https://github.com/twofas/2fas-ios/assets/1834509/e7d88399-c145-40d4-9f32-e371dfa61bce)

However, no similar message is shown when importing QR codes:

![image](https://github.com/twofas/2fas-ios/assets/1834509/afa4edd7-eb1a-4ca7-bced-44f22ff31cdf)

For a series of iOS applications, a scroll window will have a "handle" as a hint for where a page can be scroll down page. For example, the Music app has something as follows:

![image](https://github.com/twofas/2fas-ios/assets/1834509/1aba759b-88f7-4958-a6a2-e7f263197b9c)

It would be nice have something like this located at the top of the QR scan code page (and possible better tweaks to the top-bar description):

![image](https://github.com/twofas/2fas-ios/assets/1834509/bc5d6c4d-40ea-4823-9e01-efd261d1fb9e)

The application's pin security option provides only a 4-pin or 6-pin numerical entry:

![image](https://github.com/twofas/2fas-ios/assets/1834509/e8b668f1-ce75-420a-b9de-23e6cfb59b1a)

It would be cool to have additional options for extended pins, like iOS's existing passcode configurations:

![image](https://github.com/twofas/2fas-ios/assets/1834509/82f7245a-028c-41e8-af10-6fa0bad47e05)

**Comment by KobeW50** [comment]
Hi @jdknight , thank you for rising these issues and suggestions. Please open a separate github issue for each of these so that they are easier to track. Thank you
