### ISSUE TITLE
microsoft.com 2024 9 digits provided (Incorrect Secret key (only numbers 2 to 7, letters)

### ISSUE THREAD

**Issue by bcookatpcsd** [twofas/2fas-ios#77]
Microsoft account forcing mfa authentication.. 

Trying to register and they are providing a nine digit code 0-9

2fas cannot pair

![image](https://github.com/twofas/2fas-ios/assets/55087301/c8cfa47c-66bb-42f3-9d48-481a7158f923)

Advanced token settings only allows up to 8 digits.. 

(why is M$ changing things..) 

I'm sure they have a need.. but 

(other random information..)
https://superuser.com/questions/1801695/using-oathtool-instead-of-microsoft-authenticator

That's not a TOTP key – it's a pairing code specifically for Microsoft Authenticator's online setup (most likely for its "push" 2FA feature).

I don't see an option to 'choose another'.. 

![image](https://github.com/twofas/2fas-ios/assets/55087301/f5352da8-3b46-4ba9-ab2c-e2be948ef8bb)

![image](https://github.com/twofas/2fas-ios/assets/55087301/68965dbb-a8ab-43e0-aebe-af0847ae6b49)

I don't think there is a resolution here.. but possibly an opportunity to update the Q&A/Support section of 2fas

Open to suggestions.. 

Thank you in advance. 
:/

**Comment by KobeW50** [comment]
Is the 9 digit code not the secret key?

What is the length of the one-time-password that Microsoft asks you to verify when you press 'Next'?

**Comment by adocyn** [comment]
Yes, it's a Microsoft ®️ ™️ thing and not an open TOTP standard. Can't implement that, but probably there's an option on "admin" side of things to allow for standard TOTP while setting up the account. @bcookatpcsd I'm not sure if we can handle every possible case in FAQ 😄 Especially that those configurations could vary based on configuration specific to the corporation. I've seen a login which required to enter two digits from the login screen into the notification in Microsoft app just to accept it. Crazy stuff, also optional and configurable 😄
