### ISSUE TITLE
Are Secret keys saved and synced in iCloud encrypted?

### ISSUE THREAD

**Issue by toyo2333** [twofas/2fas-ios#78]
i know that the export feature support set a password。but i want to know ：Are Secret keys saved and synced in iCloud encrypted?

**Comment by tavern2782** [comment]
The community 100% absolutely needs an answer on this. 

@2fas-com @adocyn

**Comment by tavern2782** [comment]
> I am using Enpass to sync my password. The vault synced by the Onedrive or Goolge Drive is encrypted by Enpass. This is the right way.

....no, that is NOT the right way. This functionality should be contained within 2FAS. You can't honestly expect any user to follow such a complicated procedure and risk doing something wrong when Apple provides an API that supports this exact functionality. Please, stop commenting if you're going to suggest such nonsense.

**Comment by KobeW50** [comment]
Refer to https://github.com/twofas/2fas-ios/issues/43#issuecomment-1738605656
