### ISSUE TITLE
How to share tokens with a different person with a different iCloud account?

### ISSUE THREAD

**Issue by kevinp2** [twofas/2fas-ios#79]
Hi,

I would like to set up my spouse on 2FAS but ideally would like to have my app sync automatically with her app.  We would share all the tokens.  She has a different iCloud account.

Is this possible?

Any information on any workaround using export / import etc. is appreciated.

**Comment by KobeW50** [comment]
Unfortunately, cloud sync between 2 iCloud accounts is not supported (I'm not even sure if it's possible).

You can manually export/import your tokens in a local file to/from your spouse's device.
