### ISSUE TITLE
Nothing to import

### ISSUE THREAD

**Issue by dv30fps** [twofas/2fas-ios#82]
My primary phone is a Samsung Galaxy S22 Ultra. I use it to add new tokens. I also have an older iPhone without SIM, but I find that phone useful with WiFi (like a small iPad without cellular service). I transfer tokens from the Galaxy to the iPhone by exporting the data on the Galaxy to a local file. Then I upload it to my Google Drive. On the iPhone, I open the file on Google Drive with the 2FAS app on iPhone. This process has worked well until today, when I reached 25 tokens and tried to add one more.

The iOS 2FAS app reports: Nothing to import. Either the file is empty, or all the services within are already available in the app.

This message is incorrect. The file is 17 KB and cannot be empty. I added a new token making 26 on the Galaxy. The iPhone has 25, and does not recognize the new token.

I had to manually delete all the tokens in the iOS app. When I imported the file, then all 26 tokens appeared.

**Comment by adocyn** [comment]
The app is checking if the service identified by a secret already exists and filters that entries out. But from that description it looks like the file in the Google Drive could be "stale" and without the new service. I can't say anything more from this description, but there's no limit on number of services. Some users have over thousands of them.

**Comment by dv30fps** [comment]
I disagree with the evaluation because I was able to import the new token by manually removing all tokens in the iOS app and importing the same backup that produced the error message before. This is proof that the new token was present in the backup file.
