### ISSUE TITLE
Compiling the application - problem with Content/sources 0-9 files

### ISSUE THREAD

**Issue by mike-code** [twofas/2fas-ios#85]
### Question

Howdy. How to properly handle the encrypted files in the Contents/sources folder? The CONTRIBUTING.md document says to replace the two files there, but doesn't explain what should be done with the files affixed by 0-9 digits. I've tried to remove them, leaving me with
```
~/Downloads/2fas-ios-vv5.3.0/TwoFAS/Content/Sources
❯ tree
.
├── IconDescriptionDatabase.swift
├── IconDescriptionDatabaseImpl+Database.swift
├── ServiceDefinitionDatabase.swift
└── ServiceDefinitionDatabaseImpl+Database.swift
```

but that results in the following errors
![image](https://github.com/twofas/2fas-ios/assets/2964642/16fa80fa-c2e8-4ae5-b52f-473719e9b51b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adocyn** [comment]
@mike-code Hi, could you check the newest version from `develop`? I've updated the description and files.
