### ISSUE TITLE
Import tokens from Android (version of 2FAS) into old iOS

### ISSUE THREAD

**Issue by derekdai** [twofas/2fas-ios#86]
### Question

First of all, thanks for the great app!

The problem I am trying to solve is, export tokens file from Android phone (v5.3.5) onto iOS. Since I can't install latest version of 2FAS app on iOS (iPhone 7 can't upgrade to iOS >= 16), the importing end up with error because of file format it can't process. Any suggestion?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adocyn** [comment]
@derekdai The format changes because the data changed. But you can try to change `version` inside to `1` or `2` and see what happens.

**Comment by derekdai** [comment]
@adocyn Thank your for the tip. I change the `schemaVersion` from 4 to 3, now iOS can recognize the content.
