### ISSUE TITLE
bug: discord invite link expired

### ISSUE THREAD

**Issue by doc75** [twofas/2fas-ios#88]
### Bug type

Error at runtime

### App version

5.3.0

### Device environment

iOS 17.4

### Bug description

I wanted to propose new icons, but i could not connect to your discord as the invite link to your discord has expired.
I tried it from the app on iOS, but also in my web browser on Linux and same message

### Solution

Update the invite link on all your support: web site, iOS, Android, etc....

### Additional context

Not specific to iOS

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I understand that security vulnerabilities should be reported to security@2fas.com instead of on GitHub.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adocyn** [comment]
Thanks! Discord invite link updated in 5.3.5.

**Comment by doc75** [comment]
Thanks @adocyn. It is working fine now 👍
