### ISSUE TITLE
Why do you only support iOS 16.4+?

### ISSUE THREAD

**Issue by chrmel** [twofas/2fas-ios#89]
### Question

Since the latest iOS 15.x is still provided with security updates I was wondering if it was possible to support lower versions of iOS. Since your project is great, I am sure many people would benefit!

Thx and regards!

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adocyn** [comment]
@chrmel This question was already answered here https://github.com/twofas/2fas-ios/issues/37 but basically to support 3 version of OS (+ minor subversions with it's own patches, fixes and bugs) takes a lot of time and effort. Effort we would like to direct into implementing new features and day-to-day maintenance of the app. Also some of the features wouldn't work on iOS 15 right now as we're using newer API.

This is a normal cycle, which was delayed this year, but typically we're migrating to new OS version as soon as 80 - 90% of users are using it (~ November/December).

**Comment by chrmel** [comment]
Thank you for the explanation. I did not see #37 and I understand but it’s still a pity.

Is there a way to obtain/install the old version that still runs on 15.4+?
Am 21. März 2024, 16:13 +0100 schrieb Zbigniew Cisiński ***@***.***>:
