### ISSUE TITLE
bug: Can't scan QR code when time-step value is not 30

### ISSUE THREAD

**Issue by hoptodesk** [twofas/2fas-ios#90]
### Bug type

Error at runtime

### App version

5.3.5

### Device environment

iOS 17.4.1, iPhone 15

### Bug description

There is a possible bug with 2FAS when an app generates a OTP code using a value other than 30 (such as 45 for example) for the time-step value with the SHA1 algorithm, 2FAS fails to scan the QR code and shows a message "This code is incorrect or not supported. Try again.".

While testing other OTP apps, they do not appear to have this issue and can support a time-step value other than 30 seconds.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I understand that security vulnerabilities should be reported to security@2fas.com instead of on GitHub.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adocyn** [comment]
@hoptodesk That's intentional. We're not planning to support other periods. For now at least. They're very rare and we would need to redone some parts of the app like e.g. widgets, which rely on 10s steps.

**Comment by robina80** [comment]
thats a great great shame, im in the exact same boat as a website is giving me a 45second qr code to scan and i get the error

"this code is incorrect or not supported try again"

if you implemented this it would be hands down the best 2fa app out there on the market
