### ISSUE TITLE
Token sorting on Apple Watch

### ISSUE THREAD

**Issue by valynor** [twofas/2fas-ios#93]
### Bug type

Other

### App version

5.3.6

### Device environment

iPhone 13 Pro Max, 17.4.1

### Bug description

The sorting of the tokens (8) in the 2FAS app on my iPhone is alphabetical A->Z. 
The sorting on the Apple Watch companion app is different - it's _mostly_ alphabetical ;-) but there are a few tokens in the wrong place. 

Edit: Looking at the token list on the watch it could possibly be related to tokens with a space in their name. 

- [X] This issue is not a duplicate of an existing bug report.
- [X] I understand that security vulnerabilities should be reported to security@2fas.com instead of on GitHub.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adocyn** [comment]
@valynor We're using the "manual" sorting so the order is the same as on iPhone and you change services order there. But yeah, if you're using alphabetical, then it won't match the list on iPhone. I'll add to backlog other sorting options 👍

**Comment by adocyn** [comment]
@valynor This should be in release now.
