### ISSUE TITLE
More than 6 items in iPhone Widget

### ISSUE THREAD

**Issue by chris-sx** [twofas/2fas-ios#98]
### Feature description

It would be nice to have more than 6 items in iPhone Widget

### Motivation

Used 2STP until now and find that very comfortable 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adocyn** [comment]
Hi, we're not planning on redesigning the widgets right now.
