### ISSUE TITLE
Language/translation "bug" 

### ISSUE THREAD

**Issue by Panja0** [twofas/2fas-ios#99]
### Bug type

Cosmetic

### App version

iOS v5.3.6

### Device environment

iOS 17.31
iPhone 14 Pro

### Bug description

Go to settings --> Security --> App Security
I'm using Dutch as language and the sentence is correctly translated but there is an additional "word" which shouldn't be there.
As you can see on my screenshot the word **`(null)`** is at the end of the sentence and should be removed.

![IMG_2916](https://github.com/twofas/2fas-ios/assets/12939350/f56d82d0-f7bb-47d0-af92-653c3a7d51ad)

### Solution

Remove **`(null)`** from the Dutch translation.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I understand that security vulnerabilities should be reported to security@2fas.com instead of on GitHub.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by adocyn** [comment]
Thanks, we'll check that.

**Comment by gmachnio** [comment]
@Panja0, we've fixed it!
